services:
#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    restart: always
#    ports:
#      - 8445:8445
#    volumes:
#      - ./nginx:/etc/nginx/conf.d/
#    command: ['nginx', '-g', 'daemon off;']
#    depends_on:
#      - meteo
  database:
    image: mysql:8.4.0
    restart: on-failure
    container_name: database-meteo
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
      - /home/weather-data-meteo/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'weatherDB'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3307:3306" # 3307 exposed in host machine
    command: ['mysqld']

  meteo:
    image: meteo-scraper-api:latest
    container_name: meteo
    environment:
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: 'password'
    ports:
      - 8445:8445
    depends_on:
      - database
    restart: on-failure