services:
#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    restart: always
#    ports:
#      - 8445:8445
#    volumes:
#      - ./nginx:/etc/nginx/conf.d/
#    command: ['nginx', '-g', 'daemon off;']
#    depends_on:
#      - meteo
  database:
    image: postgres
    restart: on-failure
    container_name: database-meteo
    volumes:
      - /home/weather-data-meteo/:/data/postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'weatherDB'
    ports:
      - "5432:5432"
  meteo:
    image: meteo-scraper-api:latest
    container_name: meteo
    environment:
      DATABASE_USERNAME: 'root'
      DATABASE_PASSWORD: 'password'
      DATABASE_URL: 'jdbc:postgresql://database-meteo:5332/weatherDB?createDatabaseIfNotExist=true'
    ports:
      - 8445:8445
    depends_on:
      - database
    restart: on-failure