package com.emperium.utils;

import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.emperium.scraper.CityScraper;

/**
 * Class that maps the city names to an index number. The index number is used
 * in {@link CityScraper#SERVICE_URL}. According to this index, the URL for each city to be scraped is formed
 */
public class Mappings {

    public static Map<Integer, String> cityMappings = new HashMap<>();
    public static Map<String, String> monthMappings = new HashMap<>();

    public static List<LocalTime> summerTimeMappings = new ArrayList<>();
    public static List<LocalTime> winterTimeMappings = new ArrayList<>();

    static {
        cityMappings.put(1,"ΘΕΣΣΑΛΟΝΙΚΗ");
        cityMappings.put(2,"ΚΑΒΑΛΑ");
        cityMappings.put(3,"ΑΛΕΞ/ΠΟΛΗ");
        cityMappings.put(4,"ΚΟΖΑΝΗ");
        cityMappings.put(5,"ΚΕΡΚΥΡΑ");
        cityMappings.put(6,"ΠΡΕΒΕΖΑ");
        cityMappings.put(7,"ΛΗΜΝΟΣ");
        cityMappings.put(8,"ΜΥΤΙΛΗΝΗ");
        cityMappings.put(9,"ΚΕΦΑΛΟΝΙΑ");
        cityMappings.put(10,"ΠΑΤΡΑ");
        cityMappings.put(11,"ΧΙΟΣ");
        cityMappings.put(12,"ΑΘΗΝΑ - ΚΕΝΤΡΟ");
        cityMappings.put(13,"ΖΑΚΥΝΘΟΣ");
        cityMappings.put(14,"ΣΑΜΟΣ");
        cityMappings.put(15,"ΚΑΛΑΜΑΤΑ");
        cityMappings.put(16,"ΜΥΚΟΝΟΣ");
        cityMappings.put(17,"ΝΑΞΟΣ");
        cityMappings.put(18,"ΚΩΣ");
        cityMappings.put(19,"ΚΥΘΗΡΑ");
        cityMappings.put(20,"ΣΑΝΤΟΡΙΝΗ");
        cityMappings.put(21,"ΧΑΝΙΑ");
        cityMappings.put(22,"ΡΟΔΟΣ");
        cityMappings.put(23,"ΗΡΑΚΛΕΙΟ ΚΡΗΤΗΣ");
        cityMappings.put(24,"ΚΑΡΠΑΘΟΣ");
        cityMappings.put(25,"ΠΑΡΟΣ");
        cityMappings.put(26,"ΣΚΙΑΘΟΣ");
        cityMappings.put(27,"ΣΧΙΝΙΑΣ - ΜΑΡΑΘΩΝΑΣ");
        cityMappings.put(28,"ΑΓΙΟΣ ΚΟΣΜΑΣ");
        cityMappings.put(29,"ΟΛΥΜΠΙΑΚΟ ΣΤΑΔΙΟ");
        cityMappings.put(30,"ΟΛΥΜΠΙΑΚΟ ΧΩΡΙΟ");
        cityMappings.put(31,"ΙΩΑΝΝΙΝΑ");
        cityMappings.put(32,"ΛΑΡΙΣΑ");
        cityMappings.put(33,"ΒΟΛΟΣ");
        cityMappings.put(34,"ΛΑΜΙΑ");
        cityMappings.put(35,"ΝΑΥΠΑΚΤΟΣ");
        cityMappings.put(36,"ΤΡΙΠΟΛΗ");
        cityMappings.put(37,"ΑΡΓΟΣ");
        cityMappings.put(38,"ΡΕΘΥΜΝΟ");
        cityMappings.put(39,"ΑΓ.ΝΙΚΟΛΑΟΣ");
        cityMappings.put(40,"ΚΟΜΟΤΗΝΗ");
        cityMappings.put(41,"ΞΑΝΘΗ");
        cityMappings.put(42,"ΔΡΑΜΑ");
        cityMappings.put(43,"ΣΕΡΡΕΣ");
        cityMappings.put(44,"ΚΙΛΚΙΣ");
        cityMappings.put(45,"ΚΑΣΤΟΡΙΑ");
        cityMappings.put(46,"ΠΟΛΥΓΥΡΟΣ");
        cityMappings.put(47,"ΦΛΩΡΙΝΑ");
        cityMappings.put(48,"ΓΡΕΒΕΝΑ");
        cityMappings.put(49,"ΚΑΤΕΡΙΝΗ");
        cityMappings.put(50,"ΒΕΡΟΙΑ");
        cityMappings.put(51,"ΕΔΕΣΣΑ");
        cityMappings.put(52,"ΑΡΤΑ");
        cityMappings.put(53,"ΗΓΟΥΜΕΝΙΤΣΑ");
        cityMappings.put(54,"ΤΡΙΚΑΛΑ");
        cityMappings.put(55,"ΚΑΡΔΙΤΣΑ");
        cityMappings.put(56,"ΚΟΡΙΝΘΟΣ");
        cityMappings.put(57,"ΠΥΡΓΟΣ");
        cityMappings.put(58,"ΣΠΑΡΤΗ");
        cityMappings.put(59,"ΑΙΓΙΝΑ");
        cityMappings.put(60,"ΣΑΛΑΜΙΝΑ");
        cityMappings.put(61,"ΠΕΙΡΑΙΑΣ");
        cityMappings.put(62,"ΛΙΒΑΔΕΙΑ");
        cityMappings.put(63,"ΑΜΦΙΣΣΑ");
        cityMappings.put(64,"ΑΓΡΙΝΙΟ");
        cityMappings.put(65,"ΜΕΣΟΛΟΓΓΙ");
        cityMappings.put(66,"ΚΑΡΠΕΝΗΣΙ");
        cityMappings.put(67,"ΚΥΜΗ");
        cityMappings.put(68,"ΧΑΛΚΙΔΑ");
        cityMappings.put(69,"ΙΕΡΑΠΕΤΡΑ");
        cityMappings.put(70,"ΣΗΤΕΙΑ");
        cityMappings.put(71,"ΘΑΣΟΣ");
        cityMappings.put(72,"ΣΑΜΟΘΡΑΚΗ");
        cityMappings.put(73,"ΣΚΥΡΟΣ");
        cityMappings.put(74,"ΙΚΑΡΙΑ");
        cityMappings.put(75,"ΑΝΔΡΟΣ");
        cityMappings.put(76,"ΤΗΝΟΣ");
        cityMappings.put(77,"ΣΥΡΟΣ");
        cityMappings.put(78,"ΚΕΑ - ΤΖΙΑ");
        cityMappings.put(79,"ΚΥΘΝΟΣ");
        cityMappings.put(80,"ΣΕΡΙΦΟΣ");
        cityMappings.put(81,"ΣΙΦΝΟΣ");
        cityMappings.put(82,"ΜΗΛΟΣ");
        cityMappings.put(83,"ΑΜΟΡΓΟΣ");
        cityMappings.put(84,"ΚΑΛΥΜΝΟΣ");
        cityMappings.put(85,"ΛΕΥΚΑΔΑ");
        cityMappings.put(86,"ΒΟΡΕΙΑ ΠΡΟΑΣΤΙΑ");
        cityMappings.put(87,"ΝΟΤΙΑ ΠΡΟΑΣΤΙΑ");
        cityMappings.put(88,"ΒΟΡ.ΑΝΑΤ. ΠΡΟΑΣΤΙΑ");
        cityMappings.put(89,"ΔΥΤΙΚΑ ΠΡΟΑΣΤΙΑ");
        cityMappings.put(90,"ΒΟΥΛΑ - ΒΑΡΚΙΖΑ");
        cityMappings.put(91,"ΠΟΡΤΟ ΡΑΦΤΗ");
        cityMappings.put(92,"ΚΑΛΑΜΟΣ - ΩΡΩΠΟΣ");
        cityMappings.put(93,"ΚΡΥΟΝΕΡΙ ΚΟΡΙΝΘΙΑΣ");
        cityMappings.put(94,"ΚΑΛΑΒΡΥΤΑ (Χ/Κ)");
        cityMappings.put(95,"ΤΡΙΚΑΛΑ ΗΜΑΘΙΑΣ");
        cityMappings.put(96,"ΛΑΥΡΙΟ");
        cityMappings.put(97,"ΦΙΛΙΠΠΟΙ");
        cityMappings.put(98,"ΔΙΟΝ");
        cityMappings.put(99,"ΒΕΡΓΙΝΑ");
        cityMappings.put(100,"ΔΕΛΦΟΙ");
        cityMappings.put(101,"ΣΟΥΝΙΟ");
        cityMappings.put(102,"ΑΡΧΑΙΑ ΟΛΥΜΠΙΑ");
        cityMappings.put(103,"ΕΠΙΔΑΥΡΟΣ");
        cityMappings.put(104,"ΜΥΣΤΡΑΣ");
        cityMappings.put(105,"ΦΙΛΙΑΤΡΑ");
        cityMappings.put(106,"ΛΕΩΝΙΔΙΟ");
        cityMappings.put(107,"ΓΥΘΕΙΟ");
        cityMappings.put(108,"ΜΟΝΕΜΒΑΣΙΑ");
        cityMappings.put(109,"ΞΥΛΟΚΑΣΤΡΟ");
        cityMappings.put(110,"ΑΙΓΙΟ");
        cityMappings.put(111,"ΓΑΛΑΞΙΔΙ");
        cityMappings.put(112,"ΠΑΛΑΙΟΧΩΡΑ");
        cityMappings.put(113,"ΑΡΤΕΜΙΣΙΟ");
        cityMappings.put(114,"ΤΥΜΠΑΚΙ");
        cityMappings.put(115,"ΓΑΥΔΟΣ");
        cityMappings.put(116,"ΘΗΒΑ");
        cityMappings.put(117,"ΑΙΔΗΨΟΣ");
        cityMappings.put(118,"ΚΑΡΥΣΤΟΣ");
        cityMappings.put(119,"ΜΕΤΣΟΒΟ");
        cityMappings.put(120,"ΚΑΛΑΜΠΑΚΑ");
        cityMappings.put(121,"ΓΙΑΝΝΙΤΣΑ");
        cityMappings.put(122,"ΣΟΥΦΛΙ");
        cityMappings.put(123,"ΚΑΤΑΡΑ-ΑΝΗΛΙΟ");
        cityMappings.put(124,"ΣΧΗΜΑΤΑΡΙ");
        cityMappings.put(125,"ΜΑΡΤΙΝΟ");
        cityMappings.put(126,"ΣΤΥΛΙΔΑ");
        cityMappings.put(127,"ΚΑΜΕΝΑ ΒΟΥΡΛΑ");
        cityMappings.put(128,"ΠΕΡΑΜΑ - ΚΕΡΑΤΣΙΝΙ");
        cityMappings.put(129,"ΤΕΜΠΗ");
        cityMappings.put(130,"ΝΕΑ ΜΑΛΓΑΡΑ");
        cityMappings.put(131,"ΚΑΣΣΑΝΔΡΑ");
        cityMappings.put(132,"ΑΘΩΣ");
        cityMappings.put(133,"ΥΔΡΑ");
        cityMappings.put(134,"ΣΠΕΤΣΕΣ");
        cityMappings.put(135,"ΠΟΡΟΣ");
        cityMappings.put(136,"ΝΕΥΡΟΚΟΠΙ");
        cityMappings.put(137,"ΑΡΑΧΩΒΑ");
        cityMappings.put(138,"ΔΗΜΗΤΣΑΝΑ-ΣΤΕΜΝΙΤΣΑ");
        cityMappings.put(139,"ΜΕΓΑΛΟ ΧΩΡΙΟ");
        cityMappings.put(140,"ΒΙΚΟΣ/ΑΩΟΣ");
        cityMappings.put(141,"ΕΛΑΤΗ - ΠΕΡΤΟΥΛΙ-ΝΕΡΑΪΔΟΧΩΡΙ");
        cityMappings.put(142,"ΛΙΜΝΗ ΠΛΑΣΤΗΡΑ");
        cityMappings.put(143,"ΧΑΝΙΑ ΠΗΛΙΟΥ (Χ/Κ)");
        cityMappings.put(144,"ΟΛΥΜΠΟΣ-1200 μ.");
        cityMappings.put(145,"ΠΡΕΣΠΕΣ");
        cityMappings.put(146,"ΛΙΜΝΗ ΚΕΡΚΙΝΗ");
        cityMappings.put(147,"HOTEL MARINA");
        cityMappings.put(148,"ΧΑΛΚΙΑΔΕΣ ΑΡΤΑΣ");
        cityMappings.put(149,"ΝΑΟΥΣΑ");
        cityMappings.put(150,"ΚΑΣΤΑΝΙΑ ΗΜΑΘΙΑΣ");
        cityMappings.put(151,"ΔΕΡΒΕΝΙ ΘΕΣΣΑΛΟΝΙΚΗΣ");
        cityMappings.put(152,"ΑΣΠΡΟΒΑΛΤΑ");
        cityMappings.put(153,"ΒΕΥΗ ΦΛΩΡΙΝΑΣ");
        cityMappings.put(154,"ΠΤΟΛΕΜΑΪΔΑ");
        cityMappings.put(155,"ΜΑΛΑΚΑΣΑ");
        cityMappings.put(156,"Ν.ΠΕΡΑΜΟΣ");
        cityMappings.put(157,"ΕΡΥΘΡΕΣ - ΒΙΛΙΑ");
        cityMappings.put(158,"3-5 ΠΗΓΑΔΙΑ (Χ/Κ)");
        cityMappings.put(159,"ΣΕΛΙ (Χ/Κ)");
        cityMappings.put(160,"ΒΑΣΙΛΙΤΣΑ ΓΡΕΒΕΝΩΝ (Χ/Κ)");
        cityMappings.put(161,"ΚΑΪΜΑΚΤΣΑΛΑΝ (Χ/Κ)");
        cityMappings.put(162,"ΠΙΣΟΔΕΡΙ ΦΛΩΡΙΝΑΣ (Χ/Κ)");
        cityMappings.put(163,"ΛΑΪΛΙΑΣ ΣΕΡΡΩΝ (Χ/Κ)");
        cityMappings.put(164,"ΦΑΛΑΚΡΟ (Χ/Κ)");
        cityMappings.put(165,"ΑΜΥΝΤΑΙΟ");
        cityMappings.put(166,"ΚΙΝΕΤΑ");
        cityMappings.put(167,"ΜΑΚΡΑΚΩΜΗ");
        cityMappings.put(168,"ΜΥΚΗΝΕΣ");
        cityMappings.put(169,"ΟΡΕΙΝΗ ΝΑΥΠΑΚΤΙΑ");
        cityMappings.put(170,"ΙΟΣ");
        cityMappings.put(171,"ΝΑΥΠΛΙΟ");
        cityMappings.put(172,"ΟΡΕΣΤΙΑΔΑ");
        cityMappings.put(173,"ΠΑΡΓΑ");
        cityMappings.put(174,"ΜΑΚΡΙΝΙΤΣΑ ΠΟΡΤΑΡΙΑ (ΠΗΛΙΟ)");
        cityMappings.put(175,"ΣΤΕΝΗ ΕΥΒΟΙΑΣ");
        cityMappings.put(176,"ΒΛΑΣΤΗ ΚΟΖΑΝΗΣ");
        cityMappings.put(177,"ΔΟΜΟΚΟΣ");
        cityMappings.put(178,"ΣΠΗΛΙ ΡΕΘΥΜΝΟΥ");
        cityMappings.put(179,"ΔΙΔΥΜΟΤΕΙΧΟ");
        cityMappings.put(180,"ΣΟΦΑΔΕΣ ΚΑΡΔΙΤΣΑΣ");
        cityMappings.put(181,"ΕΡΕΤΡΙΑ");
        cityMappings.put(182,"ΦΟΛΟΗ ΗΛΕΙΑΣ");
        cityMappings.put(183,"ΙΘΑΚΗ");
        cityMappings.put(184,"ΚΑΤΑΡΡΑΚΤΗΣ ΑΡΤΑ");
        cityMappings.put(185,"ΣΟΥΡΠΗ ΜΑΓΝΗΣΙΑΣ");
        cityMappings.put(186,"ΖΑΧΑΡΩ ΗΛΕΙΑΣ");
        cityMappings.put(187,"ΠΑΝΑΧΑΪΚΟ ΟΡΟΣ");
        cityMappings.put(188,"ΒΟΥΡΓΑΡΕΛΙ ΑΡΤΑΣ");
        cityMappings.put(189,"ΠΟΡΤΟ-ΓΕΡΜΕΝΟ");
        cityMappings.put(190,"ΛΕΡΟΣ");
        cityMappings.put(191,"ΣΠΑΤΑ");
        cityMappings.put(192,"ΠΑΝΟΡΑΜΑ ΘΕΣΣΑΛΟΝΙΚΗΣ");
        cityMappings.put(193,"ΖΑΡΟΣ");
        cityMappings.put(194,"ΑΡΙΔΑΙΑ ΠΕΛΛΑΣ");
        cityMappings.put(195,"ΕΜΠΕΣΟΣ");
        cityMappings.put(196,"ΑΝΔΡΙΤΣΑΙΝΑ ΗΛΕΙΑΣ");
        cityMappings.put(197,"ΠΑΡΝΑΣΣΟΣ (Χ/Κ)");
        cityMappings.put(198,"ΠΡΕΒΕΛΗ");
        cityMappings.put(199,"ΟΡΧΟΜΕΝΟΣ");
        cityMappings.put(200,"ΑΓΙΟΚΑΜΠΟΣ (ΛΑΡΙΣΑ)");
        cityMappings.put(201,"ΑΡΓΑΛΑΣΤΗ");
        cityMappings.put(202,"ΣΙΘΩΝΙΑ");
        cityMappings.put(203,"ΑΜΦΙΚΛΕΙΑ");
        cityMappings.put(204,"ΑΤΑΛΑΝΤΗ");
        cityMappings.put(205,"ΚΑΣΤΕΛΛΙ");
        cityMappings.put(206,"ΜΟΙΡΕΣ ΗΡΑΚΛΕΙΟΥ");
        cityMappings.put(207,"ΑΝΩΓΕΙΑ");
        cityMappings.put(208,"ΟΥΡΑΝΟΥΠΟΛΗ");
        cityMappings.put(209,"ΤΖΕΡΜΙΑΔΩΝ");
        cityMappings.put(210,"ΣΦΑΚΙΑ");
        cityMappings.put(211,"ΑΜΑΛΙΑΔΑ");
        cityMappings.put(212,"ΚΟΝΙΤΣΑ");
        cityMappings.put(213,"ΜΕΓΑΡΑ");
        cityMappings.put(214,"ΛΟΥΤΡΑΚΙ");
        cityMappings.put(215,"ΠΑΤΜΟΣ");
        cityMappings.put(216,"ΙΣΤΙΑΙΑ");
        cityMappings.put(217,"ΚΥΠΑΡΙΣΣΙΑ");
        cityMappings.put(218,"ΤΡΙΚΑΛΑ ΚΟΡΙΝΘΙΑΣ");
        cityMappings.put(219,"ΜΠΡΑΛΟΣ");
        cityMappings.put(220,"ΚΡΙΜΙΝΙ ΚΟΖΑΝΗΣ");
        cityMappings.put(221,"ΚΑΡΠΕΝΗΣΙ (Χ/Κ)");
        cityMappings.put(222,"ΕΛΑΤΟΧΩΡΙ (Χ/Κ)");
        cityMappings.put(223,"ΚΟΝΙΣΚΟΣ ΤΡΙΚΑΛΩΝ");
        cityMappings.put(224,"ΟΡΕΙΝΗ ΦΩΚΙΔΑ");
        cityMappings.put(225,"ΣΙΔΗΡΟΚΑΣΤΡΟ ΣΕΡΡΩΝ");
        cityMappings.put(226,"ΦΑΡΣΑΛΑ");
        cityMappings.put(227,"ΝΥΜΦΑΙΟ");
        cityMappings.put(228,"ΑΣΤΑΚΟΣ ΑΙΤ/ΝΙΑΣ");
        cityMappings.put(229,"ΜΕΓΑΛΟΠΟΛΗ");
        cityMappings.put(230,"ΣΚΟΠΕΛΟΣ");
        cityMappings.put(231,"ΑΓΙΟΣ ΣΤΕΦΑΝΟΣ - ΣΤΑΜΑΤΑ - ΔΡΟΣΙΑ");
        cityMappings.put(232,"ΒΡΥΣΕΣ ΑΠΟΚΟΡΩΝΟΥ");
        cityMappings.put(233,"ΑΜΦΙΛΟΧΙΑ");
        cityMappings.put(234,"ΝΕΜΕΑ");
        cityMappings.put(235,"ΒΑΡΙΚΟ ΦΛΩΡΙΝΑΣ");
        cityMappings.put(236,"ΠΑΛΑΜΑΣ ΚΑΡΔΙΤΣΑΣ");
        cityMappings.put(237,"ΜΑΙΝΑΛΟ (Χ/Κ)");
        cityMappings.put(238,"ΠΑΡΝΗΘΑ (1000 μ)");
        cityMappings.put(239,"ΑΝΤΙΚΥΡΑ ΒΟΙΩΤΙΑΣ");
        cityMappings.put(240,"ΜΟΛΑΟΙ");
        cityMappings.put(241,"ΖΕΥΓΟΛΑΤΙΟ ΜΕΣΣΗΝΙΑΣ");
        cityMappings.put(242,"ΚΑΡΔΑΜΥΛΗ");
        cityMappings.put(243,"ΒΑΡΘΟΛΟΜΙΟ ΗΛΕΙΑΣ");
        cityMappings.put(244,"ΩΛΕΝΗ ΗΛΕΙΑΣ");
        cityMappings.put(245,"ΣΤΡΑΤΩΝΙ ΧΑΛΚΙΔΙΚΗΣ");
        cityMappings.put(247,"ΠΑΠΙΓΚΟ ΙΩΑΝΝΙΝΩΝ");
        cityMappings.put(248,"ΚΡΑΝΙΔΙ ΑΡΓΟΛΙΔΑΣ");
        cityMappings.put(249,"ΒΡΕΣΘΕΝΑ-ΠΑΡΝΩΝΑΣ");
        cityMappings.put(250,"ΜΕΣΣΗΝΗ");
        cityMappings.put(251,"ΔΩΔΩΝΗ");
        cityMappings.put(252,"ΜΟΥΣΘΕΝΗ ΚΑΒΑΛΑΣ");
        cityMappings.put(253,"ΜΕΓΑΛΗ ΒΟΛΒΗ");
        cityMappings.put(254,"ΚΗΠΟΙ ΕΒΡΟΥ");
        cityMappings.put(255,"ΑΣΠΡΟΠΥΡΓΟΣ");
        cityMappings.put(256,"ΚΟΡΩΠΙ");
        cityMappings.put(257,"ΠΑΤΡΑ - ΡΩΜΑΝΟΣ");
        cityMappings.put(258,"ΝΑΟΣ ΕΠΙΚΟΥΡΙΟΥ ΑΠΟΛΛΩΝΑ");
        cityMappings.put(259,"ΑΛΑΓΟΝΙΑ ΜΕΣΣΗΝΙΑΣ");
        cityMappings.put(260,"ΚΟΡΩΝΗ");
        cityMappings.put(261,"ΕΛΕΥΣΙΝΑ");
        cityMappings.put(262,"ΝΙΚΟΠΟΛΗ");
        cityMappings.put(263,"ΦΕΝΕΟΣ ΚΟΡΙΝΘΙΑΣ");
        cityMappings.put(264,"ΚΑΣΤΕΛΛΟΡΙΖΟ");
        cityMappings.put(265,"ΕΡΑΤΕΙΝΗ ΦΩΚΙΔΑΣ");
        cityMappings.put(266,"ΗΡΑΚΛΕΙΑ-ΣΧΟΙΝΟΥΣΑ-ΚΟΥΦΟΝΗΣΙΑ");
        cityMappings.put(268,"ΘΕΣΠΡΩΤΙΚΟ");
        cityMappings.put(269,"ΜΑΥΡΟΠΗΓΗ ΚΟΖΑΝΗΣ");
        cityMappings.put(270,"ΑΣΤΥΠΑΛΑΙΑ");
        cityMappings.put(271,"ΣΥΜΗ");
        cityMappings.put(272,"ΤΗΛΟΣ");
        cityMappings.put(273,"ΠΕΡΑΙΑ (ΘΕΣΣΑΛΟΝΙΚΗ)");
        cityMappings.put(274,"ΠΡΑΜΑΝΤΑ");
        cityMappings.put(275,"ΣΤΑΥΡΑΚΙΑ ΗΡΑΚΛΕΙΟΥ");
        cityMappings.put(276,"ΛΕΝΤΑΣ ΗΡΑΚΛΕΙΟΥ");
        cityMappings.put(277,"Αγ. ΒΑΡΒΑΡΑ ΗΡΑΚΛΕΙΟΥ");
        cityMappings.put(278,"ΑΕΡΟΔΡΟΜΙΟ ΕΔΕΣΣΑΣ");
        cityMappings.put(279,"ΛΥΚΟΧΕΙΑ ΑΡΚΑΔΙΑΣ");
        cityMappings.put(280,"ΑΡΕΟΠΟΛΗ");
        cityMappings.put(281,"ΛΕΒΙΔΙ");
        cityMappings.put(282,"ΡΑΦΗΝΑ");
        cityMappings.put(283,"ΝΙΣΥΡΟΣ");
        cityMappings.put(284,"ΜΑΝΔΡΑ");
        cityMappings.put(285,"ΜΕΘΑΝΑ");
        cityMappings.put(286,"ΑΜΥΝΤΑΙΟ-ΚΤΗΜΑ ΑΛΦΑ");
        cityMappings.put(287,"ΑΝΑΦΗ");
        cityMappings.put(288,"ΣΙΚΙΝΟΣ");
        cityMappings.put(289,"ΦΟΛΕΓΑΝΔΡΟΣ");
        cityMappings.put(291,"ΠΑΞΟΙ");
        cityMappings.put(292,"ΦΙΛΛΥΡΑ ΡΟΔΟΠΗΣ");
        cityMappings.put(293,"ΤΟΛΟ ΑΡΓΟΛΙΔΑΣ");
        cityMappings.put(294,"ΔΙΔΥΜΑ ΑΡΓΟΛΙΔΑΣ");
        cityMappings.put(295,"ΤΡΙΚΕΡΙ ΜΑΓΝΗΣΙΑΣ");
        cityMappings.put(296,"ΕΛΟΥΝΤΑ");
        cityMappings.put(297,"ΒΑΪ");
        cityMappings.put(298,"Ν. ΜΑΡΜΑΡΑΣ");
        cityMappings.put(299,"ΠΑΝΟΡΜΟΣ ΡΕΘΥΜΝΟΥ");
        cityMappings.put(300,"ΚΥΛΛΗΝΗ");
        cityMappings.put(301,"ΑΒΔΗΡΑ");
        cityMappings.put(302,"ΚΑΤΑΚΟΛΟ");
        cityMappings.put(303,"ΚΟΡΙΝΟΣ ΠΙΕΡΙΑΣ");
        cityMappings.put(304,"ΒΑΣΙΛΙΚΟ (Κεντρική Εύβοια)");
        cityMappings.put(305,"ΘΕΣΣΑΛΟΝΙΚΗ ΑΕΡΟΔΡΟΜΙΟ");
        cityMappings.put(306,"ΖΑΡΟΥΧΛΑ ΑΧΑΙΑΣ");
        cityMappings.put(307,"ΘΕΟΔΩΡΙΑΝΑ");
        cityMappings.put(308,"ΑΝΑΒΥΣΣΟΣ");
        cityMappings.put(309,"ΚΑΠΑΝΔΡΙΤΙ");
        cityMappings.put(310,"ΜΑΡΚΟΠΟΥΛΟ ΜΕΣΟΓΕΙΩΝ");
        cityMappings.put(311,"ΜΕΤΑΞΑΔΕΣ");
        cityMappings.put(312,"ΦΕΡΕΣ");
        cityMappings.put(313,"ΝΕΑ ΒΥΣΣA");
        cityMappings.put(314,"ΜΑΡΩΝΕΙΑ");
        cityMappings.put(315,"ΣΑΠΕΣ");
        cityMappings.put(316,"ΙΑΣΜΟΣ");
        cityMappings.put(317,"ΠΟΡΤΟ ΛΑΓΟΣ");
        cityMappings.put(318,"ΜΥΚΗ");
        cityMappings.put(319,"ΧΡΥΣΟΥΠΟΛΗ");
        cityMappings.put(320,"ΕΛΕΥΘΕΡΟΥΠΟΛΗ");
        cityMappings.put(321,"ΝΕΑ ΠΕΡΑΜΟΣ");
        cityMappings.put(322,"ΔΟΞΑΤΟ");
        cityMappings.put(323,"ΚΑΛΑΜΠΑΚΙ");
        cityMappings.put(324,"ΠΡΟΣΟΤΣΑΝΗ");
        cityMappings.put(325,"ΝΙΓΡΙΤΑ");
        cityMappings.put(326,"ΝΕΑ ΖΙΧΝΗ");
        cityMappings.put(327,"ΑΛΙΣΤΡΑΤΗ");
        cityMappings.put(328,"ΗΡΑΚΛΕΙΑ ΣΕΡΡΩΝ");
        cityMappings.put(329,"ΑΡΝΑΙΑ");
        cityMappings.put(330,"ΓΑΛΑΤΙΣΤΑ");
        cityMappings.put(331,"ΝΕΑ ΚΑΛΛΙΚΡΑΤΕΙΑ");
        cityMappings.put(332,"ΚΑΣΣΑΝΔΡΕΙΑ");
        cityMappings.put(333,"ΝΕΑ ΜΟΥΔΑΝΙΑ");
        cityMappings.put(334,"ΙΕΡΙΣΣΟΣ");
        cityMappings.put(335,"ΛΑΓΚΑΔΑΣ");
        cityMappings.put(336,"ΚΥΜΙΝΑ");
        cityMappings.put(337,"ΩΡΑΙΟΚΑΣΤΡΟ");
        cityMappings.put(338,"ΣΙΝΔΟΣ");
        cityMappings.put(339,"ΝΕΑ ΜΗΧΑΝΙΩΝΑ");
        cityMappings.put(340,"ΑΣΒΕΣΤΟΧΩΡΙ");
        cityMappings.put(341,"ΑΞΙΟΥΠΟΛΗ");
        cityMappings.put(342,"ΓΟΥΜΕΝΙΣΣΑ");
        cityMappings.put(343,"ΠΟΛΥΚΑΣΤΡΟ");
        cityMappings.put(344,"ΚΡΥΑ ΒΡΥΣΗ");
        cityMappings.put(345,"ΣΤΑΥΡΟΣ");
        cityMappings.put(346,"ΣΚΥΔΡΑ");
        cityMappings.put(347,"ΑΛΕΞΑΝΔΡΕΙΑ");
        cityMappings.put(348,"ΜΕΛΙΚΗ");
        cityMappings.put(349,"ΜΑΚΡΟΧΩΡΙ");
        cityMappings.put(350,"ΒΕΛΒΕΝΤΟ");
        cityMappings.put(351,"ΣΙΑΤΙΣΤΑ");
        cityMappings.put(352,"ΣΕΡΒΙΑ ΚΟΖΑΝΗΣ");
        cityMappings.put(353,"ΚΡΟΚΟΣ");
        cityMappings.put(354,"ΑΡΓΟΣ ΟΡΕΣΤΙΚΟ");
        cityMappings.put(355,"ΑΙΓΙΝΙΟ");
        cityMappings.put(356,"ΛΙΤΟΧΩΡΟ");
        cityMappings.put(357,"ΚΟΛΙΝΔΡΟΣ");
        cityMappings.put(358,"ΔΕΣΚΑΤΗ");
        cityMappings.put(359,"ΠΕΡΑΜΑ ΙΩΑΝΝΙΝΩΝ");
        cityMappings.put(360,"ΠΑΡΑΜΥΘΙΑ");
        cityMappings.put(361,"ΣΥΒΟΤΑ");
        cityMappings.put(362,"ΦΙΛΙΠΠΙΑΔΑ");
        cityMappings.put(363,"ΚΟΜΠΟΤΙ");
        cityMappings.put(364,"ΠΕΤΑ");
        cityMappings.put(365,"ΒΟΝΙΤΣΑ");
        cityMappings.put(366,"ΘΕΡΜΟ");
        cityMappings.put(367,"ΑΙΤΩΛΙΚΟ");
        cityMappings.put(368,"ΛΙΔΩΡΙΚΙ");
        cityMappings.put(369,"ΔΕΣΦΙΝΑ");
        cityMappings.put(370,"ΑΓΙΟΣ ΚΩΝ/ΝΟΣ");
        cityMappings.put(371,"ΛΙΒΑΝΑΤΕΣ");
        cityMappings.put(373,"ΣΠΕΡΧΕΙΑΔΑ");
        cityMappings.put(374,"ΣΤΥΛΙΔΑ");
        cityMappings.put(375,"ΜΑΛΕΣΙΝΑ");
        cityMappings.put(376,"ΔΙΣΤΟΜΟ");
        cityMappings.put(377,"ΒΑΓΙΑ");
        cityMappings.put(379,"ΟΙΝΟΦΥΤΑ");
        cityMappings.put(380,"ΑΛΙΑΡΤΟΣ");
        cityMappings.put(381,"ΑΥΛΙΔΑ");
        cityMappings.put(382,"ΑΜΑΡΥΝΘΟΣ");
        cityMappings.put(383,"ΔΡΟΣΙΑ ΕΥΒΟΙΑΣ");
        cityMappings.put(384,"ΒΑΣΙΛΙΚΑ (Βόρεια Εύβοια)");
        cityMappings.put(385,"ΑΛΙΒΕΡΙ");
        cityMappings.put(386,"ΝΕΑ ΑΡΤΑΚΗ");
        cityMappings.put(387,"ΨΑΧΝΑ");
        cityMappings.put(388,"ΚΑΤΩ ΑΧΑΙΑ");
        cityMappings.put(389,"ΟΒΡΥΑ");
        cityMappings.put(390,"ΠΑΡΑΛΙΑ ΑΧΑΙΑΣ");
        cityMappings.put(391,"ΓΑΣΤΟΥΝΗ");
        cityMappings.put(392,"ΚΡΕΣΤΕΝΑ");
        cityMappings.put(393,"ΑΝΔΡΑΒΙΔΑ");
        cityMappings.put(394,"ΛΕΧΑΙΝΑ");
        cityMappings.put(395,"ΛΑΓΚΑΔΙΑ");
        cityMappings.put(396,"ΑΣΤΡΟΣ");
        cityMappings.put(397,"ΣΚΑΛΑ");
        cityMappings.put(398,"ΝΕΑΠΟΛΗ ΒΟΙΩΝ");
        cityMappings.put(400,"ΠΥΛΟΣ");
        cityMappings.put(401,"ΓΑΡΓΑΛΙΑΝΟΙ");
        cityMappings.put(402,"ΛΥΓΟΥΡΙΟ");
        cityMappings.put(403,"ΕΡΜΙΟΝΗ");
        cityMappings.put(404,"ΠΟΡΤΟ ΧΕΛΙ");
        cityMappings.put(405,"ΝΕΑ ΚΙΟΣ");
        cityMappings.put(406,"ΒΕΛΟ");
        cityMappings.put(408,"ΚΙΑΤΟ");
        cityMappings.put(409,"ΜΟΛΥΒΟΣ");
        cityMappings.put(410,"ΛΙΝΔΟΣ");
        cityMappings.put(411,"ΑΡΧΑΓΓΕΛΟΣ");
        cityMappings.put(412,"ΙΑΛΥΣΟΣ");
        cityMappings.put(413,"ΚΡΕΜΑΣΤΗ");
        cityMappings.put(414,"ΜΟΥΡΝΙΕΣ");
        cityMappings.put(415,"ΦΑΛΑΣΑΡΝΑ");
        cityMappings.put(416,"ΚΙΣΣΑΜΟΣ");
        cityMappings.put(417,"ΑΡΚΑΛΟΧΩΡΙ");
        cityMappings.put(418,"ΓΑΖΙ");
        cityMappings.put(419,"ΜΑΛΙΑ");
        cityMappings.put(420,"ΤΑΥΓΕΤΟΣ; - ΚΑΤΑΦΥΓΙΟ");
        cityMappings.put(421,"ΝΕΑ ΑΛΙΚΑΡΝΑΣΣΟΣ");
        cityMappings.put(422,"ΑΡΧΑΝΕΣ");
        cityMappings.put(423,"ΝΕΑΠΟΛΗ ΛΑΣΙΘΙΟΥ");
        cityMappings.put(424,"ΑΛΜΥΡΟΣ");
        cityMappings.put(425,"Ν. ΑΓΧΙΑΛΟΣ");
        cityMappings.put(426,"ΒΕΛΕΣΤΙΝΟ");
        cityMappings.put(427,"ΑΓΙΑ");
        cityMappings.put(428,"ΑΜΠΕΛΩΝΑΣ");
        cityMappings.put(429,"ΕΛΑΣΣΟΝΑ");
        cityMappings.put(430,"ΤΥΡΝΑΒΟΣ");
        cityMappings.put(432,"ΝΕΟΧΩΡΙ-ΟΙΧΑΛΙΑ");
        cityMappings.put(433,"ΦΑΡΚΑΔΟΝΑ");
        cityMappings.put(434,"ΠΥΛΗ");
        cityMappings.put(435,"ΜΟΥΖΑΚΙ");
        cityMappings.put(437,"ΠΑΡΑΝΕΣΤΙ");
        cityMappings.put(438,"ΑΛΟΝΝΗΣΟΣ");
        cityMappings.put(439,"ΚΑΣΟΣ");
        cityMappings.put(440,"ΑΜΑΡΙ");
        cityMappings.put(441,"ΝΕΣΤΟΡΙΟ");
        cityMappings.put(442,"ΑΓΝΑΝΤΑ");
        cityMappings.put(443,"ΑΝΕΖΑ ΑΡΤΑΣ");
        cityMappings.put(444,"ΑΓ. ΑΘΑΝΑΣΙΟΣ ΠΕΛΛΑ");
        cityMappings.put(445,"ΖΗΡΕΙΑ Χ/Κ");
        cityMappings.put(446,"ΓΡΑΜΜΟΣ");
        cityMappings.put(447,"ΚΑΛΑΒΡΥΤΑ");
        cityMappings.put(448,"ΝΕΑ ΖΙΧΝΗ ΣΕΡΡΩΝ");
        cityMappings.put(449,"ΣΤΡΥΜΟΝΙΚΟ ΣΕΡΡΩΝ");
        cityMappings.put(450,"ΣΟΧΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ");
        cityMappings.put(451,"ΛΑΧΑΝΑΣ ΘΕΣΣΑΛΟΝΙΚΗΣ");
        cityMappings.put(452,"ΑΣΣΗΡΟΣ ΘΕΣΣΑΛΟΝΙΚΗΣ");
        cityMappings.put(453,"ΚΟΥΦΑΛΙΑ ΘΕΣΣΑΛΟΝΙΚΗΣ");
        cityMappings.put(454,"ΑΨΑΛΟΣ ΠΕΛΛΑΣ");
        cityMappings.put(455,"ΔΡΟΣΑΤΟ ΚΙΛΚΙΣ");
        cityMappings.put(456,"ΜΕΛΙΤΗ ΦΛΩΡΙΝΑΣ");
        cityMappings.put(457,"ΝΕΑΠΟΛΗ ΚΟΖΑΝΗΣ");
        cityMappings.put(458,"ΡΙΖΩΜΑΤΑ ΗΜΑΘΙΑΣ");
        cityMappings.put(459,"ΤΣΟΤΥΛΙ ΚΟΖΑΝΗΣ");
        cityMappings.put(460,"ΣΚΟΤΙΝΑ ΠΙΕΡΙΑΣ");
        cityMappings.put(461,"ΠΛΑΤΑΜΩΝΑΣ ΠΙΕΡΙΑΣ");
        cityMappings.put(462,"ΚΡΑΝΙΑ ΕΛΑΣΣΟΝΑΣ");
        cityMappings.put(463,"ΠΛΑΤΥΚΑΜΠΟΣ ΛΑΡΙΣΑΣ");
        cityMappings.put(464,"ΣΤΕΦΑΝΟΒΙΚΙ ΜΑΓΝΗΣΙΑΣ");
        cityMappings.put(465,"ΖΑΓΟΡΑ ΜΑΓΝΗΣΙΑΣ");
        cityMappings.put(466,"ΠΤΕΛΕΟΣ ΜΑΓΝΗΣΙΑΣ");
        cityMappings.put(467,"ΣΑΓΙΑΔΑ ΘΕΣΠΡΩΤΙΑΣ");
        cityMappings.put(468,"ΦΙΛΙΑΤΕΣ ΘΕΣΠΡΩΤΙΑΣ");
        cityMappings.put(469,"ΚΑΝΑΛΑΚΙ ΠΡΕΒΕΖΑΣ");
        cityMappings.put(470,"ΔΕΛΒΙΝΑΚΙ ΙΩΑΝΝΙΝΩΝ");
        cityMappings.put(471,"ΛΕΠΕΝΟΥ ΑΙΤ/ΝΙΑΣ");
        cityMappings.put(472,"ΙΤΕΑ");
        cityMappings.put(473,"ΕΥΠΑΛΙΟ");
        cityMappings.put(474,"ΠΟΛΥΔΡΟΣΟ ΦΩΚΙΔΑΣ");
        cityMappings.put(475,"ΤΙΘΟΡΕΑ ΦΘΙΩΤΙΔΑΣ");
        cityMappings.put(476,"ΠΕΛΑΣΓΙΑ ΦΘΙΩΤΙΔΑΣ");
        cityMappings.put(477,"ΜΩΛΟΣ ΦΘΙΩΤΙΔΑΣ");
        cityMappings.put(478,"ΜΑΚΡΑΚΩΜΗ ΦΘΙΩΤΙΔΑΣ");
        cityMappings.put(479,"ΛΙΑΝΟΚΛΑΔΙ ΦΘΙΩΤΙΔΑΣ");
        cityMappings.put(480,"ΤΑΝΑΓΡΑ");
        cityMappings.put(481,"ΚΥΡΙΑΚΙ ΒΟΙΩΤΙΑΣ");
        cityMappings.put(482,"ΑΥΛΩΝΑΣ");
        cityMappings.put(483,"ΧΩΡΑ ΜΕΣΣΗΝΙΑΣ");
        cityMappings.put(484,"ΜΕΘΩΝΗ");
        cityMappings.put(485,"ΑΚΡΑΤΑ");
        cityMappings.put(486,"ΜΑΝΩΛΑΔΑ");
        cityMappings.put(487,"ΒΑΡΔΑ ΗΛΕΙΑΣ");
        cityMappings.put(488,"ΓΑΛΑΤΑΣ ΤΡΟΙΖΗΝΙΑΣ");
        cityMappings.put(489,"ΚΡΟΚΕΕΣ ΛΑΚΩΝΙΑΣ");
        cityMappings.put(490,"ΓΕΡΑΚΙ ΛΑΚΩΝΙΑΣ");
        cityMappings.put(491,"ΓΕΡΓΕΡΗ ΗΡΑΚΛΕΙΟΥ");
        cityMappings.put(492,"ΚΡΟΥΣΣΩΝΑΣ ΗΡΑΚΛΕΙΟΥ");
        cityMappings.put(493,"ΖΑΚΡΟΣ ΛΑΣΙΘΙΟΥ");
        cityMappings.put(494,"ΚΑΝΔΑΝΟΣ ΧΑΝΙΩΝ");
        cityMappings.put(495,"ΧΙΛΙΟΜΟΔΙ-ΚΟΥΤΑΛΑΣ ΚΟΡΙΝΘΙΑΣ");
        cityMappings.put(496,"ΖΙΤΣΑ ΙΩΑΝΝΙΝΩΝ");
        cityMappings.put(497,"ΜΑΝΤΟΥΔΙ ΕΥΒΟΙΑΣ");
        cityMappings.put(498,"ΒΥΤΙΝΑ ΑΡΚΑΔΙΑΣ");
        cityMappings.put(499,"ΑΓΡΑΦΑ ΕΥΡΥΤΑΝΙΑΣ");
        cityMappings.put(500,"ΑΝΩ ΒΙΑΝΝΟΣ");
    }

    static {
        monthMappings.put("ΙΑΝΟΥΑΡΙΟΥ",  "01");
        monthMappings.put("ΦΕΒΡΟΥΑΡΙΟΥ", "02");
        monthMappings.put("ΜΑΡΤΙΟΥ",     "03");
        monthMappings.put("ΑΠΡΙΛΙΟΥ",    "04");
        monthMappings.put("ΜΑΪΟΥ",       "05");
        monthMappings.put("ΙΟΥΝΙΟΥ",     "06");
        monthMappings.put("ΙΟΥΛΙΟΥ",     "07");
        monthMappings.put("ΑΥΓΟΥΣΤΟΥ",   "08");
        monthMappings.put("ΣΕΠΤΕΜΒΡΙΟΥ", "09");
        monthMappings.put("ΟΚΤΩΒΡΙΟΥ",   "10");
        monthMappings.put("ΝΟΕΜΒΡΙΟΥ",   "11");
        monthMappings.put("ΔΕΚΕΜΒΡΙΟΥ",  "12");
    }

    static {
        summerTimeMappings.add(0, LocalTime.parse("03:00"));
        summerTimeMappings.add(1, LocalTime.parse("06:00"));
        summerTimeMappings.add(2, LocalTime.parse("09:00"));
        summerTimeMappings.add(3, LocalTime.parse("12:00"));
        summerTimeMappings.add(4, LocalTime.parse("15:00"));
        summerTimeMappings.add(5, LocalTime.parse("18:00"));
        summerTimeMappings.add(6, LocalTime.parse("21:00"));
        summerTimeMappings.add(7, LocalTime.parse("00:00"));
    }

    static {
        winterTimeMappings.add(0, LocalTime.parse("02:00"));
        winterTimeMappings.add(1, LocalTime.parse("05:00"));
        winterTimeMappings.add(2, LocalTime.parse("08:00"));
        winterTimeMappings.add(3, LocalTime.parse("11:00"));
        winterTimeMappings.add(4, LocalTime.parse("14:00"));
        winterTimeMappings.add(5, LocalTime.parse("17:00"));
        winterTimeMappings.add(6, LocalTime.parse("20:00"));
        winterTimeMappings.add(7, LocalTime.parse("23:00"));
    }
}